
import java.io.FileWriter;
import java.io.IOException;
import java.util.Set;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author FS
 */
public class LU5_Prog_Cafe_GUI extends javax.swing.JFrame {

    /**
     * Creates new form LU5_Prog_Cafe_GUI
     */
    public LU5_Prog_Cafe_GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        label_Title = new javax.swing.JLabel();
        label_MainIngredient = new javax.swing.JLabel();
        label_BreadChoices = new javax.swing.JLabel();
        cmb_MainIngredient = new javax.swing.JComboBox<>();
        cmb_BreadChoices = new javax.swing.JComboBox<>();
        label_Toppings = new javax.swing.JLabel();
        cbx_Lettuce = new javax.swing.JCheckBox();
        cbx_Cheese = new javax.swing.JCheckBox();
        cbx_BellPeppers = new javax.swing.JCheckBox();
        cbx_Tomatoe = new javax.swing.JCheckBox();
        label_Toasted = new javax.swing.JLabel();
        rbtn_Toasted = new javax.swing.JRadioButton();
        rbtn_NonToasted = new javax.swing.JRadioButton();
        label_Instructions = new javax.swing.JLabel();
        label_OrderSummary = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea_SpecialInstructions = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtArea_Summary = new javax.swing.JTextArea();
        btn_OrderSummary = new javax.swing.JButton();
        btn_SavetoTextFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label_Title.setFont(new java.awt.Font("Inter", 3, 12)); // NOI18N
        label_Title.setForeground(new java.awt.Color(255, 153, 102));
        label_Title.setText("Prog Cafe - Sandwich Order App");
        label_Title.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label_MainIngredient.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        label_MainIngredient.setText("Main Ingredient:");

        label_BreadChoices.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        label_BreadChoices.setText("Bread Choices: ");

        cmb_MainIngredient.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        cmb_MainIngredient.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chicken", "Beef", "Veggie Patty", "Tuna" }));
        cmb_MainIngredient.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 255, 0)));

        cmb_BreadChoices.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "White Bread", "Whole-Wheat Bread", "Italian Bread", "Gluten-Free", "Rye Bread" }));

        label_Toppings.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        label_Toppings.setText("Toppings: ");

        cbx_Lettuce.setText("Lettuce");

        cbx_Cheese.setText("Cheese");

        cbx_BellPeppers.setText("Bell Peppers");
        cbx_BellPeppers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_BellPeppersActionPerformed(evt);
            }
        });

        cbx_Tomatoe.setText("Tomatoe");

        label_Toasted.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        label_Toasted.setText("Toasted Choice:");

        buttonGroup1.add(rbtn_Toasted);
        rbtn_Toasted.setText("Toasted");

        buttonGroup1.add(rbtn_NonToasted);
        rbtn_NonToasted.setText("Non-Toasted");

        label_Instructions.setText("Special Instructions:");

        label_OrderSummary.setText("Order Summary:");

        txtArea_SpecialInstructions.setColumns(20);
        txtArea_SpecialInstructions.setRows(5);
        jScrollPane1.setViewportView(txtArea_SpecialInstructions);

        txtArea_Summary.setEditable(false);
        txtArea_Summary.setColumns(20);
        txtArea_Summary.setLineWrap(true);
        txtArea_Summary.setRows(5);
        txtArea_Summary.setWrapStyleWord(true);
        jScrollPane2.setViewportView(txtArea_Summary);

        btn_OrderSummary.setBackground(new java.awt.Color(102, 204, 255));
        btn_OrderSummary.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        btn_OrderSummary.setText("Display Order Summary");
        btn_OrderSummary.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        btn_OrderSummary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_OrderSummaryActionPerformed(evt);
            }
        });

        btn_SavetoTextFile.setText("Save Order Summary");
        btn_SavetoTextFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SavetoTextFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(label_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(label_Toppings)
                                    .addComponent(label_Toasted))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbtn_Toasted)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtn_NonToasted))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(cbx_Lettuce, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbx_Cheese, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(cbx_BellPeppers, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(17, 17, 17)
                                    .addComponent(label_MainIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmb_MainIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(label_BreadChoices))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(label_OrderSummary)
                                        .addComponent(label_Instructions))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_Tomatoe, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_BreadChoices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(btn_OrderSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(btn_SavetoTextFile)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label_Title, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_MainIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_MainIngredient, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label_BreadChoices)
                    .addComponent(cmb_BreadChoices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Toppings)
                    .addComponent(cbx_Lettuce)
                    .addComponent(cbx_Cheese)
                    .addComponent(cbx_BellPeppers)
                    .addComponent(cbx_Tomatoe))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_Toasted)
                    .addComponent(rbtn_NonToasted)
                    .addComponent(rbtn_Toasted))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(label_Instructions))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(label_OrderSummary)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_OrderSummary)
                    .addComponent(btn_SavetoTextFile))
                .addGap(163, 163, 163))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbx_BellPeppersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_BellPeppersActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbx_BellPeppersActionPerformed

    private void btn_OrderSummaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_OrderSummaryActionPerformed
       generateOrderSummary(); //method call to the logic behind the button behaviour
    }//GEN-LAST:event_btn_OrderSummaryActionPerformed

    private void btn_SavetoTextFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SavetoTextFileActionPerformed
        saveOrder(); //method call to the logic behind the button behaviour
    }//GEN-LAST:event_btn_SavetoTextFileActionPerformed

    //Logic to save the order summary to a text file
    private void saveOrder()
    {   
        String summary = txtArea_Summary.getText();
        if(summary.isEmpty())
        {
            JOptionPane.showMessageDialog(this, "Please generate an order summary first!");
            return;      
        }
        try (FileWriter writer = new FileWriter("order_summary.txt"))
        {
            writer.write(summary);
            JOptionPane.showMessageDialog(this, "Order saved successfully!");
        }
        catch (IOException ex)
        {
            JOptionPane.showMessageDialog(this, "Error saving order to the text file: " + ex.getMessage());
        }
    
    }
    
    
    
  // Logic to generate the order summary
private void generateOrderSummary() {
    try {
        // Holding the user-selected option in a variable called 'bread'
        String bread = cmb_BreadChoices.getSelectedItem().toString();
        String mainIngredient = cmb_MainIngredient.getSelectedItem().toString();

        // Combine selected toppings using a StringBuilder
        StringBuilder toppings = new StringBuilder();
        if (cbx_Lettuce.isSelected()) 
            toppings.append("Lettuce, ");
        if (cbx_Cheese.isSelected()) 
            toppings.append("Cheese, ");
        if (cbx_BellPeppers.isSelected()) 
            toppings.append("Bell Peppers, ");
        if (cbx_Tomatoe.isSelected()) 
            toppings.append("Tomatoe, ");
        
        //remove trailing spaces / commas
        if(toppings.length() > 0)
        {
            toppings.setLength(toppings.length() - 2);
        }
   
        // Check if the user opted for a toasted sandwich
        boolean isToasted = rbtn_Toasted.isSelected();

        // Get the text from the special instructions area
        String instructions = txtArea_SpecialInstructions.getText();

        // Format the order summary
        String summary = String.format(
            "Bread: "
                    + "%s\nMain Ingredient: "
                    + "%s\nToppings: "
                    + "%s\nToasted: "
                    + "%s\nSpecial Instructions: "
                    + "%s",bread, mainIngredient, toppings.toString(), (isToasted ? "Yes" : "No"), instructions
        );

        // Set the generated summary into the text area
        txtArea_Summary.setText(summary);

    } catch (Exception ex) {
        JOptionPane.showMessageDialog(
            null, "Error generating order summary: " + ex.getMessage()
        );
    }
}
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LU5_Prog_Cafe_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LU5_Prog_Cafe_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LU5_Prog_Cafe_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LU5_Prog_Cafe_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LU5_Prog_Cafe_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_OrderSummary;
    private javax.swing.JButton btn_SavetoTextFile;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.JCheckBox cbx_BellPeppers;
    private javax.swing.JCheckBox cbx_Cheese;
    private javax.swing.JCheckBox cbx_Lettuce;
    private javax.swing.JCheckBox cbx_Tomatoe;
    private javax.swing.JComboBox<String> cmb_BreadChoices;
    private javax.swing.JComboBox<String> cmb_MainIngredient;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_BreadChoices;
    private javax.swing.JLabel label_Instructions;
    private javax.swing.JLabel label_MainIngredient;
    private javax.swing.JLabel label_OrderSummary;
    private javax.swing.JLabel label_Title;
    private javax.swing.JLabel label_Toasted;
    private javax.swing.JLabel label_Toppings;
    private javax.swing.JRadioButton rbtn_NonToasted;
    private javax.swing.JRadioButton rbtn_Toasted;
    private javax.swing.JTextArea txtArea_SpecialInstructions;
    private javax.swing.JTextArea txtArea_Summary;
    // End of variables declaration//GEN-END:variables
}
